# Generated by Django 6.0 on 2025-12-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=50)),
                ('Code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='hod_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.BigIntegerField()),
                ('Department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.department_model')),
            ],
        ),
        migrations.CreateModel(
            name='professor_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.BigIntegerField()),
                ('Subject', models.CharField(max_length=50)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department_model')),
            ],
        ),
        migrations.CreateModel(
            name='student_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Register_id', models.CharField(max_length=50)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department_model')),
                ('HOD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.hod_model')),
            ],
        ),
    ]
